### ISSUE TITLE
request: output option

### ISSUE THREAD

**Issue by shellscape** [nolanlawson/cjs-to-es6#10]
Ahoy. Thanks for putting this module together. I'm intending to use it to generate an `mjs` file from a CommonJS in an automated prepublish step. One drawback right now is that I can't specify a file to output to; the file I specify to convert is just overwritten. It's a mild inconvenience, as I just have to copy the file to the new extension before running cjs-to-es6.

So being able to specify `--out` or some such would be keen.

**Comment by nolanlawson** [comment]
Thanks for opening this issue! I'm no longer maintaining this library, so I've noted that in the instance description. PRs welcome though. :)

**Comment by nolanlawson** [comment]
This is an old issue, but I would recommend looking at how `cjs-to-es6` works and writing your own tool to do what you describe. Thanks!

**Comment by nolanlawson** [comment]
Great suggestion, thank you.
