### ISSUE TITLE
tried to convert appium.js. It seems does not work.

### ISSUE THREAD

**Issue by mittalri** [nolanlawson/cjs-to-es6#14]
C:\Users\Ritesh Mittal\AppData\Roaming\npm\node_modules\appium\lib>cjs-to-es6 --verbose appium.js

Ahoy! ES6ifyin' your CommonJS for ya...

Found 1 files.

Transforming require() to import ...
Processing 1 files...
Spawning 1 workers...
Sending 1 files to free worker...
All done.
Results:
0 errors
1 unmodified
0 skipped
0 ok
Time elapsed: 1.170seconds

Transforming module.exports/exports to export ...
Processing 1 files...
Spawning 1 workers...
Sending 1 files to free worker...
All done.
Results:
0 errors
1 unmodified
0 skipped
0 ok
Time elapsed: 1.215seconds

ES6ification complete!

**Comment by nolanlawson** [comment]
Hi, you could try with the latest package which is a rewrite. `--verbose` may show some useful output.

Closing this issue for now, please reopen if you have more details. Thanks!
