### ISSUE TITLE
Awkward code doesn't get converted

### ISSUE THREAD

**Issue by brandonros** [nolanlawson/cjs-to-es6#2]
```
var graph = module.exports;

graph.utilities = require('./utilities.js');
graph.events = require('./events.js');
graph.redraw = require('./redraw.js').redraw;

```

Transform error.

**Comment by nolanlawson** [comment]
Yeah stuff like this typically isn't supported because it's fairly impossible to statically analyze.

**Comment by brandonros** [comment]
Awesome. I figured it out.

After all that, I ended up rolling back to CJS. Browserify + rollupify doesn't bring the performance benefits mentioned in your blog article, right?

**Comment by nolanlawson** [comment]
It brings them partially, yes. But only if you have a lot of first-party modules.
