### ISSUE TITLE
cjs-to-es6 should offer a way to invoke "named-export-generation" transform on the converted modules

### ISSUE THREAD

**Issue by ivosh** [nolanlawson/cjs-to-es6#6]
Many of my CommonJS modules export an object via module.exports.

5to6-codemod/exports transform basically renames "module exports" to "export default".
But I need 5to6-codemod/named-export-generation transform to happen afterwards, so that
I have also named exports in the converted ES6 module.

CommonJS:
`module.exports = {export1, export2}`

ES6 after 'exports' transform:
`export default {export1, export2}`

ES6 after 'named-export-generation' (the desired state):
`export {export1, export2}`

Could you introduce for example a new command line option for this purpose?

**Comment by nolanlawson** [comment]
I don't know of any way to enable this? This library is basically just a CLI over https://github.com/5to6/5to6-codemod. Perhaps that library has some way to enable this?

**Comment by nolanlawson** [comment]
closing old issues, please reopen as necessary
